### ISSUE TITLE
A bug fix for Kuboard CI/CD integratio

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#58]
1. Update the `build.yaml` file as follows:

```
......
......
    outputs:
      # Image name
      image-name:
        description: URL for docker image 
        value: ${{ jobs.build.outputs.image-name }}
      # Image tag (version)
      image-tag:
        description: image tag(version)
        value: ${{ jobs.build.outputs.image-tag }}
......
......
```

2. Update the deployment files for each environment (`mainnet.yaml`, `staging.yaml`, `testnet.yaml`) as follows:

```
......
......
    with:
      k8s-namespace: staging
      k8s-workload: ${{ matrix.workload }}
      image-name: ${{ needs.build.outputs.image-name }}
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets: inherit
......
......
```

3. Update the `update-image.yaml` file as follows:
In the update-image.yaml file, the PUT request data content is updated and a new step is added to display the results of the request after it returns. The `Restart container` step is also deleted as it is meaningless in this workflow. This fix resolves an issue with Kuboard CI/CD integration where the update-image.yaml file was not able to update the name and version of the Docker image correctly.

```
......
......
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print image name
        run: echo ${{ inputs.image }}
      - name: Update image on K8S
        id: http-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.KUBOARD_API_URL }}/cluster/ckb/kind/CICDApi/ops/resource/updateImageTag
          method: 'PUT'
          customHeaders: '{"Content-Type": "application/json", "Cookie": "KuboardUsername=${{ secrets.KUBOARD_USERNAME }}; KuboardAccessKey=${{ secrets.KUBOARD_ACCESS_KEY }}"}'
          data: '{"kind":"deployments","namespace":"${{ inputs.k8s-namespace }}","name":"${{ inputs.k8s-workload }}","images":{"${{ inputs.image-name }}":"${{ inputs.image-name }}:${{ inputs.image-tag }}"}}'
      - name: Display Response
        run: |
            echo "Response response: ${{ steps.http-request.outputs.response }}"
            echo "Response headers: ${{ steps.http-request.outputs.headers }}"
......
......
```
@zmcNotafraid @rabbitz @Keith-CY
