### ISSUE TITLE
Optimize the problem of too long push image time in CI/CD

### ISSUE THREAD

**Issue by guomaoqiu** [Magickbase/infra#82]
Since the docker-build-push plug-in used uses the `--all-tags` parameter when pushing after each package build, it will upload all the built images in the runner. As time accumulates, the build time will also increase. The longer it is, it will have a certain impact on the development progress. This is currently a known issue and has been reported to the author. Other methods are being tested to avoid this issue.

![Image](https://github.com/Magickbase/infra/assets/9714859/ec830a5f-51bd-4737-ba8e-3dd4b5e78664)

**Comment by guomaoqiu** [comment]
📢📢📢 **`build.yml` configuration optimization update:**
Please directly copy the following content to cover the develop/.github/workflows/build.yml file


```
name: Pull, build docker image and push to repository
on:
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true
    outputs:
      # Image name
      image-name:
        description: URL for docker image
        value: ${{ jobs.build.outputs.image-name }}
      # Image tag (version)
      image-tag:
        description: image tag(version)
        value: ${{ jobs.build.outputs.image-tag }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-name: "${{ steps.docker_build.outputs.imageFullName }}"
      image-tag: "${{ steps.docker_build.outputs.tags }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ckb-explorer-api
          registry: ghcr.io
          githubOrg: magickbase # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: DeleteUselessImages
        run: docker images && docker images| grep "ckb-explorer-api" | grep -v "IMAGE ID" | awk 'NR>1 {print $3}' | xargs -I {}  docker rmi {}
      - name: CheckImage
        run: docker images && df -hT && df -ih
```
Test on the develop branch. @rabbitz @zmcNotafraid
